apiVersion: apps/v1
kind: Deployment
metadata:
  name: lapzone
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lapzone
  template:
    metadata:
      labels:
        app: lapzone
    spec:
     containers:
       - name: django
         image: didin8080/lapzone:latest
         ports:
           - containerPort: 8000
